### PR TITLE
Fix duplicated bytes in streaming retries

### LINKED ISSUE #2692: S3 - retrying fetches can corrupt the downloaded file?
### Describe the bug

We've been seeing some very occasional file corruption when downloading files from S3 using the SDK. We first observed this on 2nd March, and have had 6 occurrences since (out of, say, 20,000 successful downloads).

The affected files have a repeated chunk in them - say the original file is 5MB, the resulting file after download might be 5.5MB, with the first 0.5MB being repeated twice.

```ruby
s3 = ::Aws::S3::Resource.new(region: s3_config[:region], credentials: s3_credentials)
s3.bucket(bucket_name)
s3.object(key).get(response_target: local_path, checksum_mode: "ENABLED")
```

After downloading, the file at `local_path` should match the S3 object. However, we're still seeing this silently corrupt the download despite the presence of checksum_mode.

### Expected Behavior

Downloaded files exactly match the file on S3. Or, at least, a checksum error is raised if they don't match.

### Current Behavior

Whenever we've seen this fail, the file takes longer than usual to download, and the SDK logger reports that a retry was used: 

```
[Aws::S3::Client 200 75.615772 1 retries] get_object(checksum_mode:"ENABLED",bucket:"XXXXXX",key:"YYYY")  
```

Here's the S3 logs from that:

```
36f9b0673892ff12e83df3b8d5de28c2ce25d3f004d8d9789e008a752773f3ec BUCKET [20/Apr/2022:17:49:20 +0000] MY_IP MY_ROLE FS9KQCP2K686GR6H REST.GET.OBJECT KEY "GET /BUCKET/KEY HTTP/1.1" 200 - 18216449 35600463 91928 130 "-" "aws-sdk-ruby3/3.130.0 ruby/3.0.3 x86_64-linux aws-sdk-s3/1.113.0" - gEh8Wuxn1GM4Az2bZSKFZntpUrV0SjBCmUKAK0HDIII625xheiSywECi1K26a5PoxVv3YcM2SCc= SigV4 ECDHE-RSA-AES128-GCM-SHA256 AuthHeader s3.amazonaws.com TLSv1.2 -

36f9b0673892ff12e83df3b8d5de28c2ce25d3f004d8d9789e008a752773f3ec BUCKET [20/Apr/2022:17:50:33 +0000] MY_IP MY_ROLE 2KZRM5108Z74T3BD REST.GET.OBJECT KEY "GET /BUCKET/KEY HTTP/1.1" 200 - 35600463 35600463 906 92 "-" "aws-sdk-ruby3/3.130.0 ruby/3.0.3 x86_64-linux aws-sdk-s3/1.113.0" - PyjzB9K05cmGg2NbJnwRJcEJbFlIHr05lpfww/O7qOe6Izj7GHz/yt9bfZHXDzjlVqMHLdxYL4M= SigV4 ECDHE-RSA-AES128-GCM-SHA256 AuthHeader s3.amazonaws.com TLSv1.2 -

```

In this example, the S3 file is 35,600,463 bytes long, but the corrupted local file is 36,036,229 with a duplicated 435,766 byte section at the start.

### Reproduction Steps

I'm open to better ideas to reproduce this but have tried for a while without success. Sometimes weeks go by without us seeing the issue.

### Possible Solution

_No response_

### Additional Information/Context

This is also opened as AWS support ticket 9950331191 with unredacted info, if you have any access to that

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 3.130.0

### Environment details (Version of Ruby, OS environment)

Ruby 3.0.3, Ubuntu 18

### PR DESCRIPTION
**Pull request by alextwoods**
Fixes: #2692 

Rewind the underlying file on a streaming retry that is not a truncated body.

Testing and reproduction:
It is difficult to test/reproduce the issue, but can be done by modifying the net http handler:
```
net_resp.read_body do |chunk|
  bytes_received += chunk.bytesize
  resp.signal_data(chunk)
  if chunk.bytesize > 1000 && Thread.current[:raise_network]
    Thread.current[:raise_network] = nil
    raise NetworkingError.new(SocketError.new, "Test transient networking error")
  end
end
```

Note: Working on developing automated testing.

And then:
```
Thread.current[:raise_network] = true # hack this into handler.rb line 88.
key = "download_corruption_test"
s3 = ::Aws::S3::Resource.new
bucket = s3.bucket(bucket_name)
bucket.object(key).get(response_target: 'tmp.out', checksum_mode: "ENABLED")
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Review by mullermp — APPROVED** [review]

File: gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/streaming_retry.rb [hunk 1]
```diff
@@ -84,8 +95,19 @@ def add_event_listeners(context, target)
             end
 
             context.http_response.on_error do |error|
-              if retryable_body?(context) && truncated_body?(error)
-                context.http_request.headers[:range] = "bytes=#{context.http_response.body.size}-"
+              puts context.http_response.body
```
Comment (jdelStrother) [inline gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/streaming_retry.rb:98]: Is this going to stdout? Wasn't sure if this was intentional or left over from debugging

Comment (alextwoods) [reply gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/streaming_retry.rb:98]: Great catch, will remove!
