### PR TITLE
Fix s3 download ranges for chunks

### LINKED ISSUE #2859: aws-sdk-s3 fails when downloading file of exactly 20971524 bytes from S3 bucket bug
### Describe the bug

Hi,

Using FileDownloader's multithreaded download, downloading a file that is exactly 20971524 bytes long results in an `Aws::S3::Errors::InvalidRange` (The requested range is not satisfiable) exception.

The issue comes from what looks like a off-by-one error, resulting in that case in an invalid range for that last chunk.

### Expected Behavior

File should obviously be downloadable without an exception due to incorrect math/logic :)

### Current Behavior

```
[Aws::S3::Client 206 12.824679 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=0-5242880")  
[Aws::S3::Client 206 12.635049 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=5242881-10485761")  
[Aws::S3::Client 206 15.445052 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=10485762-15728642")  
[Aws::S3::Client 206 11.991756 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=15728643-20971523")  
[Aws::S3::Client 416 0.804207 0 retries] get_object(bucket:"xxx",key:"yyy.jpeg",range:"bytes=20971524-20971524") Aws::S3::Errors::InvalidRange The requested range is not satisfiable
```

The last chunk is empty/non existant, resulting in the exception.

### Reproduction Steps

Any 20971524 bytes long file should show the error, using default `download_file` options.

### Possible Solution

From my understanding, instead of downloading chunks that are MIN_CHUNK_SIZE (= 5242880 bytes) long, the code currently downloads chunks that are MIN_CHUNK_SIZE+1 long.

A file that is 20971524 bytes long should be downloaded as 4 5242880-bytes parts + a last 4-bytes part (20971524 = 5242880 * 4 + 4): 5 parts in total.
However, as the code downloads 5242880+1 bytes parts, we currently have 4*5242881 parts plus a final... 0-byte part (which is invalid).

Possible solutions:
- avoid building empty chunks
- fix `construct_chunks` to build `default_chunk_size` long parts instead of `default_chunk_size+1` (then, also check that a file that is exactly 4*5242880 bytes long gets downloaded in 4 parts w/o a final empty part)

### Additional Information/Context

See also https://github.com/aws/aws-sdk-ruby/issues/2561

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

Ruby 3.1, 3.2, Linux

### PR DESCRIPTION
**Pull request by mullermp**
Fixes #2859
Related to #2563

### CODE REVIEW

File: gems/aws-sdk-s3/spec/object/download_file_spec.rb [hunk 1]
```diff
@@ -179,53 +182,6 @@ module S3
               ":chunk_size shouldn't exceed total file size."
             )
         end
-
-        context 'file size is chunk size boundary' do
```
Comment (alextwoods) [inline gems/aws-sdk-s3/spec/object/download_file_spec.rb:183]: It seems like we should still keep a similar test.

I think we should likely also have a test that size=min_chunk_size uses single_request.

**Review by alextwoods — COMMENTED** [review]
Looks good overall - but I do think its worth expanding on tests a little.

File: gems/aws-sdk-s3/spec/object/download_file_spec.rb (hunk 1 above)
Comment (mullermp) [reply gems/aws-sdk-s3/spec/object/download_file_spec.rb:183]: I think the mock that I added will work in all cases. It verifies that there's no range where the bytes are equal. There's already a case here where it's on the boundary, too.

Comment (mullermp) [reply gems/aws-sdk-s3/spec/object/download_file_spec.rb:183]: 1 byte ranges apparently work..

**Review by alextwoods — APPROVED** [review]
LGTM!

**Comment by cmaion** [comment]
:+1:

File: gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb [hunk 2]
```diff
@@ -58,15 +58,15 @@ def multipart_download
         resp = @client.head_object(@params.merge(part_number: 1))
         count = resp.parts_count
         if count.nil? || count <= 1
-          if resp.content_length <= MIN_CHUNK_SIZE
+          if resp.content_length < MIN_CHUNK_SIZE
```
Comment (cmaion) [inline gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb]: I believe you can keep the `<=` operator: no need to fire a single thread for A MIN_CHUNK_SIZE bytes long file, as it will be downloaded in a single chunk anyway.

File: gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb [hunk 3]
```diff
@@ -58,15 +58,15 @@ def multipart_download
...
             single_request
           else
             multithreaded_get_by_ranges(construct_chunks(resp.content_length))
           end
         else
           # partNumber is an option
           resp = @client.head_object(@params)
-          if resp.content_length <= MIN_CHUNK_SIZE
```
Comment (cmaion) [inline gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb]: Same here

File: gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb (hunk 2 above)
Comment (mullermp) [reply gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb]: I didn't want to change behavior if I didn't have to. I think changing this could break some test expectations for some customers. This code is old as dirt.

Comment (mullermp) [reply gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb]: I think we can roll with it anyway. The optimization is worth it.

Comment (cmaion) [reply gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb]: Oh ok sorry, I misread a commit. I didn't see that it's currently <, but you changed it to <= then back to < :smiley: 
I agree, <= should be harmless :+1:
