### PR TITLE
Ensure SSOCredentials expiration is a time

### LINKED ISSUE #2874: Can't create S3 presigned URLs
### Describe the bug

Trying to create a presigned URL with `object.presigned_url(:get)` results in a `TypeError`.

### Expected Behavior

The method call should return a valid presigned URL for S3

### Current Behavior

A `TypeError` is raised:
```
/Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sigv4-1.6.0/lib/aws-sigv4/signer.rb:729:in `-': Time can't be coerced into Integer (TypeError)
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sigv4-1.6.0/lib/aws-sigv4/signer.rb:729:in `presigned_url_expiration'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sigv4-1.6.0/lib/aws-sigv4/signer.rb:426:in `presign_url'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/presigner.rb:243:in `block in sign_but_dont_send'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/seahorse/client/plugins/request_callback.rb:87:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/streaming_retry.rb:71:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/s3_signer.rb:73:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:17:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/xml/error_handler.rb:10:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/s3_signer.rb:48:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/redirects.rb:20:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/user_agent.rb:37:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/http_checksum.rb:19:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:136:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:23:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:21:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/rest/handler.rb:10:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/endpoints.rb:41:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:84:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/skip_whole_multipart_get_checksums.rb:18:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/presigner.rb:187:in `block in handle_presigned_url_context'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-core-3.176.0/lib/seahorse/client/request.rb:72:in `send_request'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/presigner.rb:148:in `_presigned_request'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/presigner.rb:79:in `presigned_url'
	from /Users/trusanen/ruby-test/vendor/bundle/ruby/2.6.0/gems/aws-sdk-s3-1.127.0/lib/aws-sdk-s3/customizations/object.rb:219:in `presigned_url'
	from init.rb:7:in `<main>'
```

### Reproduction Steps

With the following Gemfile and script, the `TypeError` is raised with `bundle install --path vendor/bundle && bundle exec ruby init.rb`

Gemfile
```
source 'https://rubygems.org'
gem 'aws-sdk-core', '3.176.0'
gem 'aws-sdk-s3', '1.127.0'
gem 'aws-sdk-kms', '~> 1'
gem 'aws-sigv4', '1.6'
```

Script
```
require 'aws-sdk-s3'

resource = Aws::S3::Resource.new
object = resource.bucket('my-bucket').object('my-object')
puts object.presigned_url(:get)
```

### Possible Solution

There seems to be a bug in the recently added `presigned_url_expiration` method.

### Additional Information/Context

Tested with aws-sdk-core (3.174.0), aws-sdk-s3 (1.126.0) and aws-sigv4 (1.5.0) and with these versions the method call works as expected and a valid presigned URL is printed to the console.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core (3.176.0), aws-sdk-s3 (1.127.0), aws-sigv4 (1.6.0)

### Environment details (Version of Ruby, OS environment)

ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]

### PR DESCRIPTION
**Pull request by alextwoods**
Fixes #2874 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

File: gems/aws-sdk-core/lib/aws-sdk-core/sso_credentials.rb [hunk 1]
```diff
@@ -158,7 +158,7 @@ def refresh
         c.secret_access_key,
         c.session_token
       )
-      @expiration = c.expiration
+      @expiration = Time.at(c.expiration / 1000.0)
```
Comment (mullermp) [inline gems/aws-sdk-core/lib/aws-sdk-core/sso_credentials.rb:161]: Why /1000.0 ?

File: gems/aws-sdk-core/spec/aws/sso_credentials_spec.rb [hunk 2]
```diff
@@ -135,6 +135,13 @@ def mock_token_file(start_url, cached_token)
           sso_creds.credentials
         end
       end
+
+      describe '#expiration' do
+        it 'is a time' do
+          sso_creds = SSOCredentials.new(sso_opts)
+          expect(sso_creds.expiration).to be_a(Time)
```
Comment (mullermp) [inline gems/aws-sdk-core/spec/aws/sso_credentials_spec.rb:143]: I want to verify that sso_creds.expiration is expiration here.

**Review by mullermp — APPROVED** [review]
