### PR TITLE
Fix error when attempting to format an unlinked tempfile

### LINKED ISSUE #3163: Error when uploading a file to ActiveStorage from a request body
### Describe the bug

I am receiving an uploaded file as the request body in a Rails request, which I am then forwarding directly to ActiveStorage which uses S3 as it's backend.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

The file should be uploaded correctly to S3.

### Current Behavior

An error occurs when the AWS SDK is trying to create a log of the upload. Without too much digging, it appears that it is trying to retrieve file information for the request body, which may not be an actual file on disk, rather a different sort of I/O object.

Stack trace below:

```
gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:61:in `File.size': No such file or directory @ rb_file_s_size - /tmp/puma20250109-55-6s7703 (Errno::ENOENT)
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:61:in `Aws::Log::ParamFormatter#summarize_file'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:54:in `Aws::Log::ParamFormatter#summarize_value'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:31:in `block in Aws::Log::ParamFormatter#summarize_symbol_hash'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:30:in `Hash#each'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:30:in `Enumerable#map'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:30:in `Aws::Log::ParamFormatter#summarize_symbol_hash'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:26:in `Aws::Log::ParamFormatter#summarize_hash'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/param_formatter.rb:18:in `Aws::Log::ParamFormatter#summarize'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/formatter.rb:136:in `Aws::Log::Formatter#_request_params'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/formatter.rb:107:in `block in Aws::Log::Formatter#format'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/formatter.rb:107:in `String#gsub'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/log/formatter.rb:107:in `Aws::Log::Formatter#format'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/logging.rb:62:in `Aws::Plugins::Logging::Handler#format'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/logging.rb:55:in `Aws::Plugins::Logging::Handler#log'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/logging.rb:45:in `block in Aws::Plugins::Logging::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/logging.rb:43:in `Aws::Plugins::Logging::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `Seahorse::Client::Plugins::RaiseResponseErrors::Handler#call'
    from gems/aws-sdk-s3-1.177.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `Aws::S3::Plugins::SseCpk::Handler#call'
    from gems/aws-sdk-s3-1.177.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `Aws::S3::Plugins::Dualstack::OptionHandler#call'
    from gems/aws-sdk-s3-1.177.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `Aws::S3::Plugins::Accelerate::OptionHandler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `Aws::Plugins::ChecksumAlgorithm::OptionHandler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `Aws::Plugins::JsonvalueConverter::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/invocation_id.rb:16:in `Aws::Plugins::InvocationId::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `Aws::Plugins::IdempotencyToken::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/param_converter.rb:26:in `Aws::Plugins::ParamConverter::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/seahorse/client/plugins/request_callback.rb:89:in `Seahorse::Client::Plugins::RequestCallback::OptionHandler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/response_paging.rb:12:in `Aws::Plugins::ResponsePaging::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/seahorse/client/plugins/response_target.rb:24:in `Seahorse::Client::Plugins::ResponseTarget::Handler#call'
    from gems/aws-sdk-rails-5.1.0/lib/aws/rails/notifications.rb:22:in `block in Aws::Rails::Notifications::Handler#call'
    from gems/activesupport-8.0.1/lib/active_support/notifications.rb:212:in `ActiveSupport::Notifications.instrument'
    from gems/aws-sdk-rails-5.1.0/lib/aws/rails/notifications.rb:21:in `Aws::Rails::Notifications::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/telemetry.rb:39:in `block in Aws::Plugins::Telemetry::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/telemetry/no_op.rb:29:in `Aws::Telemetry::NoOpTracer#in_span'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/telemetry.rb:53:in `Aws::Plugins::Telemetry::Handler#span_wrapper'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/telemetry.rb:39:in `Aws::Plugins::Telemetry::Handler#call'
    from gems/aws-sdk-core-3.214.1/lib/seahorse/client/request.rb:72:in `Seahorse::Client::Request#send_request'
    from gems/aws-sdk-s3-1.177.0/lib/aws-sdk-s3/client.rb:17185:in `Aws::S3::Client#put_object'
    from gems/aws-sdk-s3-1.177.0/lib/aws-sdk-s3/object.rb:2956:in `block in Aws::S3::Object#put'
    from gems/aws-sdk-core-3.214.1/lib/aws-sdk-core/plugins/user_agent.rb:60:in `Aws::Plugins::UserAgent.metric'
    from gems/aws-sdk-s3-1.177.0/lib/aws-sdk-s3/object.rb:2955:in `Aws::S3::Object#put'
    from gems/activestorage-8.0.1/lib/active_storage/service/s3_service.rb:134:in `ActiveStorage::Service::S3Service#upload_with_single_part'
    from gems/activestorage-8.0.1/lib/active_storage/service/s3_service.rb:33:in `block in ActiveStorage::Service::S3Service#upload'
    from gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `block in ActiveSupport::Notifications.instrument'
    from gems/activesupport-8.0.1/lib/active_support/notifications/instrumenter.rb:58:in `ActiveSupport::Notifications::Instrumenter#instrument'
    from gems/activesupport-8.0.1/lib/active_support/notifications.rb:210:in `ActiveSupport::Notifications.instrument'
    from gems/activestorage-8.0.1/lib/active_storage/service.rb:165:in `ActiveStorage::Service#instrument'
    from gems/activestorage-8.0.1/lib/active_storage/service/s3_service.rb:29:in `ActiveStorage::Service::S3Service#upload'
    from gems/activestorage-8.0.1models/active_storage/blob.rb:272:in `ActiveStorage::Blob#upload_without_unfurling'
    from gems/activestorage-8.0.1models/active_storage/blob.rb:97:in `block in ActiveStorage::Blob.create_and_upload!'
    from gems/activestorage-8.0.1models/active_storage/blob.rb:96:in `ActiveStorage::Blob.create_and_upload!'
```

### Reproduction Steps

My controller code is as follows:

```ruby
def upload
  filename = params.require!(:filename)
  blob = ActiveStorage::Blob.create_and_upload!(io: request.body, filename:)
end
```

### Possible Solution

I have patched the SDK with the following code as a workaround:

```ruby
module AwsLogParamFormatter
  def summarize_file path
    return "#<File:#{path} (doesn't exist)>" unless File.exist?(path)

    super
  end
end

Aws::Log::ParamFormatter.prepend(AwsLogParamFormatter)
```

That produces log entries as follows:

```
[Aws::S3::Client 200 0.258169 0 retries] put_object(body:#<File:/tmp/puma20250109-54-doexe9 (doesn't exist)>,content_md5:"bHguYZMIx/15yEM5wVhsSQ==",content_type:"application/pdf",content_disposition:nil,metadata:{},bucket:"bucket-name",key:"5yk6v4wfea7vgox7aqkv72dbi251")
```

### Additional Information/Context

This has begun happening after upgrading to the latest version of Ruby, Rails and the SDK, so while I've marked it as a regression it may have been caused by Ruby or Rails.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core 3.214.1, aws-sdk-s3 1.177.0

### Environment details (Version of Ruby, OS environment)

Ruby 3.4.1, Rails 8.0.1

### PR DESCRIPTION
**Pull request by adamdebono**
Fixes #3163

This resolves an issue where a `File` object can be available to the running Ruby program, but no longer exist on disk. Previously, the log formatter would check a file's size using its path, this now uses the instance's `size` method.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb [hunk 1]
```diff
@@ -43,15 +47,18 @@ def format(pattern, options = {})
             config: {
               nested: true,
               path: Pathname.new(__FILE__),
+              tmpfile:,
```
Comment (mullermp) [inline gems/aws-sdk-core/spec/aws/log/formatter_spec.rb]: This will fail older rubies. I would also just call this "file" to match the case statement.

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb [hunk 2]
```diff
@@ -34,6 +34,10 @@ def format(pattern, options = {})
         end
 
         it 'provides a :request_params replacement' do
```
Comment (mullermp) [inline gems/aws-sdk-core/spec/aws/log/formatter_spec.rb:36]: If this test is acting like a kitchen sink, it would be appreciated if we can test all the possibilities in the case statement. Would you mind adding an array here too?

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb [hunk 3]
```diff
@@ -34,6 +34,10 @@ def format(pattern, options = {})
...
+          tmpfile = Tempfile.create
+          File.unlink(tmpfile.path) unless RUBY_DESCRIPTION.match?(/mswin|ming|cygwin/)
```
Comment (mullermp) [inline gems/aws-sdk-core/spec/aws/log/formatter_spec.rb]: Can we link a comment to the issue on why we should exclude these?

**Review by mullermp — APPROVED** [review]

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb (hunk 1 above)
Comment (adamdebono) [reply gems/aws-sdk-core/spec/aws/log/formatter_spec.rb]: Fixed, although the `file` key is marked as sensitive [here](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb#L19), so it would be filtered in the output. I've left it as `tmpfile`, but can change that to something else if you wish.

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb (hunk 2 above)
Comment (adamdebono) [reply gems/aws-sdk-core/spec/aws/log/formatter_spec.rb:36]: done

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb (hunk 3 above)
Comment (adamdebono) [reply gems/aws-sdk-core/spec/aws/log/formatter_spec.rb]: done

**Review by alextwoods — APPROVED** [review]
Nice!  Thanks for the fix!

**Review by jterapin — APPROVED** [review]
