### PR TITLE
Require rest endpoint params

### LINKED ISSUE #2304: Aws::S3::Client#delete_object deletes the bucket when key is set to empty string
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution

```
aws-sdk-s3 (1.61.1)
```  

**Describe the bug**
The documentation for `Aws::S3::Client#delete_object` specifies that [`:key` is a required parameter](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#delete_object-instance_method). However, if the `key` is an empty string (`""`) but the `bucket` name is provided, parameter validation passes and the client attempts to delete the bucket.

In my case, this occurred because the key was derived from a response from an external service. The field from which the key was derived happened to be an empty key in the response. Fortunately, the bucket was _not_ empty and an `Aws::S3::Errors::BucketNotEmpty` error was raised. However, a bucket that happened to be empty would have been inadvertently deleted.

**Version of Ruby, OS environment**
```
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
```

**To Reproduce (observed behavior)**
```ruby
client = AWS::S3::Client.new
client.delete_object(bucket: 'my-bucket', key: '')
#=> Aws::S3::Errors::BucketNotEmpty: The bucket you tried to delete is not empty
```

**Expected behavior**
`Aws::S3::Client#delete_object` should not attempt to the delete the bucket when the `key` is set to an empty string (`""`).

The following is what happens if you specify a `bucket` but pass a `key` that is `nil`:
```ruby
client = AWS::S3::Client.new
client.delete_object(bucket: 'my-bucket', key: nil)
#=> ArgumentError: missing required parameter params[:key]
```
Perhaps a similar parameter validation error could be raised when the key is an empty string.

**Additional context**
I realize there's some ambiguity as to what the behavior really _should_ be here based on how one interprets the word "required" in the docs. If nothing else, maybe the documentation could be updated to be clear that this could occur. That said, considering the alternative is accidentally deleting a bucket (even an empty one), I think raising an `ArgumentError` might be more appropriate.

### PR DESCRIPTION
**Pull request by mullermp**
Fixes #2304

Also allows for s3 presigner to presign list_objects.. can maybe lump that change in.

Specs will need fixing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mullermp** [comment]
```
Aws> s3.delete_object(bucket: 'mamuller-us-west-2', key: '')
ArgumentError: :key must not be blank
from /Users/mamuller/workplace/aws-sdk-ruby/gems/aws-sdk-core/lib/aws-sdk-core/rest/request/endpoint.rb:40:in `param_value_for_placeholder'
```

File: gems/aws-sdk-core/spec/aws/xml/error_handler_spec.rb [hunk 1]
```diff
@@ -135,10 +135,10 @@ module Xml
       end
 
       it 'handles route53 error format with message' do
-        stub_request(:post, 'https://route53.amazonaws.com/2013-04-01/hostedzone//rrset/').
+        stub_request(:post, 'https://route53.amazonaws.com/2013-04-01/hostedzone/ResourceId/rrset/').
           to_return(:status => 400, :body => route53_error)
         expect {
-          route53.change_resource_record_sets
+          route53.change_resource_record_sets(hosted_zone_id: "ResourceId")
```
Comment (alextwoods) [inline gems/aws-sdk-core/spec/aws/xml/error_handler_spec.rb:141]: My fault on this - but use single quotes.
