### PR TITLE
Fix up documentation around customized S3 object

### LINKED ISSUE #1967: Passing in a closed `Tempfile` to `Aws::S3::FileUploader#upload` raises
### Issue description

`Aws::S3::FileUploader#upload` does not properly handle closed a closed `Tempfile`. I triggered this issue by passing a closed `Tempfile` to `Aws::S3::Object#upload_file`. Read the section below for more details.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3 1.30.1

### Version of Ruby, OS environment

Ubuntu Linux, ruby 2.4.5p335

### Code snippets / steps to reproduce

The issue is a bit tricky and may actually be a bug in the Ruby VM itself, but should be relatively easy to work around in the S3 gem.

Before diving into the S3 gem itself, please note this behavior from Ruby:

```
[25] pry(main)> n=Tempfile.new('hi'); n.write('hi'); n.close; n.size
=> 2
[26] pry(main)> File.size(n)
IOError: closed stream
from (pry):26:in `size'
```

In other words: `Tempfile#size` works fine, but `File.size` raises. Why this happens is a bit tricky and may be a bug in the Ruby VM.

The issue is that internally in the Ruby VM a call to `File.size` will check if the file is open and raise if it is not. 

See the following pieces of code:
1.  First, the call to `File.size` (which calls `rb_stat`): https://github.com/ruby/ruby/blob/ruby_2_4/file.c#L1953-L1973
2.  Next, the call to `rb_stat` (which calls `GetOpenFile`): https://github.com/ruby/ruby/blob/ruby_2_4/file.c#L1007-L1022
3.  Next, the call to `GetOpenFile` (which calls `rb_io_check_closed`): https://github.com/ruby/ruby/blob/ruby_2_4/include/ruby/io.h#L120
4.  Finally the code in `rb_io_check_closed` which triggers the raise: https://github.com/ruby/ruby/blob/ruby_2_4/io.c#L638-L645

In contrast, the `Tempfile#size` method itself will first check if the file is open or closed and avoid the raise in `File.size` by passing in the `Tempfile#path` to `File.size` instead. See this code from `Tempfile#size`: https://github.com/ruby/ruby/blob/ruby_2_4/lib/tempfile.rb#L224-L232

Compare that code to the code in `Aws::S3::FileUploader`: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/file_uploader.rb#L26-L36

`Aws::S3::FileUploader#upload` triggers the raise because it does not do the same check that `Tempfile#size` is doing.

My suggestion on how to resolve this would be one of the following:
1.  If this behavior is desired, update the comment to indicate that only an open `Tempfile` can be passed to `upload_file`, or
2.  Update the code so that `Tempfile#size` is called in `Aws::S3::FileUploader#upload` which avoids this issue entirely

### PR DESCRIPTION
**Pull request by mullermp**
This change updates documentation around Object#upload_file, as well as some general code clean-up via Rubocop and pending tests.

I bounced back and forth on adding a check for Tempfiles to determine its size, but decided that the doc updates made more sense. A change would allow closed Tempfiles to be uploaded but not closed Files, and that was inconsistent.

Closes #1967, #2120

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb [hunk 1]
```diff
@@ -320,29 +328,31 @@ def upload_file(source, options = {})
...
       #  `get_range` mode allows `chunk_size` parameter to configured in
       #  customizing each range size in multipart_download,
       #  By default, `auto` mode is enabled, which performs multipart_download
       #
-      # @option options [String] chunk_size required in get_range mode
+      # @option options [String] chunk_size required in get_range mode.
       #
-      # @option options [String] thread_count Customize threads used in multipart
-      #   download, if not provided, 10 is default value
+      # @option options [String] thread_count (10) Customize threads used in the
```
Comment (cjyclaire) [inline gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb]: still have string here?

File: gems/aws-sdk-s3/spec/object_spec.rb [hunk 2]
```diff
@@ -3,6 +3,13 @@
 module Aws
   module S3
     class Object
+
+      pending '#copy_from'
```
Comment (cjyclaire) [inline gems/aws-sdk-s3/spec/object_spec.rb]: pending?

File: gems/aws-sdk-s3/spec/object_spec.rb [hunk 3]
```diff
@@ -14,6 +21,17 @@ class Object
         end
 
       end
+
```
Comment (cjyclaire) [inline gems/aws-sdk-s3/spec/object_spec.rb]: also here?

File: gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb (hunk 1 above)
Comment (mullermp) [reply gems/aws-sdk-s3/lib/aws-sdk-s3/customizations/object.rb]: Yeah - I changed it (locally) as well as some other stuff. I will update soon.

**Comment by cjyclaire** [comment]
Make sure fix CI before merging
