### PR TITLE
Apply checksums to MultipartStreamUploader

### LINKED ISSUE #2769: Error when providing checksum_algorithm to object.stream_upload
### Describe the bug

The AWS S3 documentation implies that I can specify a ChecksumAlgorithm when starting a streaming upload, and that the SDK will automagically calculate the checksum of uploaded data, and provide it to S3 at the completion of the upload:

https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#trailing-checksums

And in fact I see references to this in the `gems/aws-sdk-s3/CHANGELOG.md` file, but am having trouble getting it to work. I tried:

```
object.upload_stream({checksum_algorithm: "CRC32"}) do |s3_stream|
```

But I get back: **Aws::S3::Errors::InvalidRequest The upload was created using a crc32 checksum. The complete request must include the checksum for each part. It was missing for part 1 in the request.**

### Expected Behavior

Streaming uploads should support a trailing checksum as per AWS documentation.

### Current Behavior

Aws::S3::Errors::InvalidRequest The upload was created using a crc32 checksum. The complete request must include the checksum for each part. It was missing for part 1 in the request.

### Reproduction Steps

object = bucket.object("my-bucket-name")
object.upload_stream(:checksum_algorithm => "CRC32") do |s3_stream|
    s3_stream.upload "a bunch of data"
end

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

### PR DESCRIPTION
**Pull request by alextwoods**
Fixes #2769 

This applies the same changes from https://github.com/aws/aws-sdk-ruby/pull/2668 to the [MultipartStreamUploader](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_stream_uploader.rb)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

File: gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_stream_uploader.rb [hunk 1]
```diff
@@ -26,6 +26,10 @@ class MultipartStreamUploader
       UPLOAD_PART_OPTIONS =
         Set.new(Client.api.operation(:upload_part).input.shape.member_names)
 
+      # @api private
+      COMPLETE_OPTIONS =
```
Comment (mullermp) [inline gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_stream_uploader.rb]: The full name here would be less confusing

**Review by mullermp — COMMENTED** [review]
Nice!
