### PR TITLE
Fix abort on exceptions

### LINKED ISSUE #2946: Errors downloading files from s3 are propagated to incorrect thread
### Describe the bug

While downloading files from S3, any exceptions are propagated to the main thread instead of the calling thread.

This appears to be due to the use of `Thread.abort_on_exception` (see https://github.com/aws/aws-sdk-ruby/blob/e0115affb56b42a08917e14950f730ae89c38183/gems/aws-sdk-s3/lib/aws-sdk-s3/file_downloader.rb#L193 ).

### Expected Behavior

Exceptions propagate to the calling context

### Current Behavior

Exceptions are propagated to the main thread, interrupting unrelated code.

### Reproduction Steps

```
workers = []
workers << Thread.new do
  begin
    Aws::S3::Object.new(bucket_name: "test", key: "fails_to_download").download_file("outputfile")
  rescue
    puts "We should get here if the download failed, but do not."
  end
end
workers.each &:join

puts "We should get here regardless of the download failing or succeeding, but do not"
```

Because the error is propagated to the main thread instead of the calling thread, and the main thread has no exception handler, the process aborts unexpectedly.

### Possible Solution

Instead of using `abort_on_exception`, store the calling thread at the start of `download_in_threads` and use `calling_thread.raise(exception)` to propagate errors.

### Additional Information/Context

_No response_

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

3.2.2 / linux

### PR DESCRIPTION
**Pull request by jterapin**
Fixes #2946 

* Removing `abort_on_exception` for  `file_downloader`, `multipart_stream_uploader` and `multipart_file_uploader`
* Updated existing specs
* After reviews, planning to update outdated styling
---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

File: gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_file_uploader.rb [hunk 1]
```diff
@@ -175,7 +175,6 @@ def upload_in_threads(pending, completed, options)
               error
             end
           end
-          thread.abort_on_exception = true
```
Comment (jterapin) [inline gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_file_uploader.rb:178]: I was tracking down how errors are raised for both `multipart_file_uploader` and `multipart_stream_uploader`. Below is a breakdown for `multipart_file_uploader` but the stream uploader is pretty similar:
* Errors are rescued instead of raised: https://github.com/aws/aws-sdk-ruby/blob/2f0e6f83473c59d6f4875694ae8cb386a9894a61/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_file_uploader.rb#L172
* All the errors are collected to `threads_errors` and then passed to abort multipart upload call: 
  * https://github.com/aws/aws-sdk-ruby/blob/2f0e6f83473c59d6f4875694ae8cb386a9894a61/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_file_uploader.rb#L79 
  * https://github.com/aws/aws-sdk-ruby/blob/2f0e6f83473c59d6f4875694ae8cb386a9894a61/gems/aws-sdk-s3/lib/aws-sdk-s3/multipart_file_uploader.rb#L86

Removing `abort_on_exception` should be _ok_ here.

The `file_downloader.rb` is bit different since we raise the error in its own thread. With the removal of `abort_on_exception`, we shouldn't cause any interruption in the main thread.

File: gems/aws-sdk-s3/spec/object/download_file_spec.rb [hunk 2]
```diff
@@ -221,17 +221,34 @@ module S3
...
           thread = double(value: nil)
-          allow(thread).to receive(:abort_on_exception=)
           expect(Thread).to receive(:new).and_yield.and_return(thread)
 
           expect do
             large_obj.download_file(path)
           end.to raise_error(Aws::Errors::ChecksumError)
         end
 
+        it 'does not interrupt the main thread when an exception occurs' do
```
Comment (mullermp) [inline gems/aws-sdk-s3/spec/object/download_file_spec.rb]: Probably not necessary because we're removing functionality here.

**Review by mullermp — COMMENTED** [review]
Can you investigate whether this code is still needed and if it needs changing? https://github.com/aws/aws-sdk-ruby/blob/e652c549c2b9ae41d7fc7b62ec4733eb1b15a42e/gems/aws-sdk-core/spec/shared_spec_helper.rb#L44-L53

File: gems/aws-sdk-s3/spec/object/download_file_spec.rb (hunk 2 above)
Comment (jterapin) [reply gems/aws-sdk-s3/spec/object/download_file_spec.rb]: Whoah. The `threat_report_on_exception` flag is cool. I was actually wondering on how I can go about removing the exception clutter left between specs. I found the PR when this was implemented: https://github.com/aws/aws-sdk-ruby/pull/2307

I want to say that it would be nice to keep it since the below spec has it: 
https://github.com/aws/aws-sdk-ruby/blob/ed4f82ecc9e141aafa2fd20bd24719db839510d3/gems/aws-sdk-s3/spec/object/multipart_copy_spec.rb#L371

Without this, this spec prints (7) long exception errors.

Also dropped the spec I wrote.

**Review by mullermp — APPROVED** [review]
