### PR TITLE
Handle sso session names with quotes/spaces

### LINKED ISSUE #2894: SDK fails to use SSO credentials configured via `aws configure sso`
### Describe the bug

After configuring a profile using `aws configure sso --profile PROFILENAME`, the `aws` CLI tool can use the configured profile using `aws --profile PROFILENAME` without trouble (all commands that I've tried work), but the AWS SDK for Ruby fails with an error, when trying to configure it with that profile.

### Expected Behavior

Setting the named profile through the `Aws.config` options should work for SSO profile as well as it does for static profiles:

```
$ irb -r aws-sdk-ec2
irb(main):001:0> Aws::EC2::Client.new({profile: 'PROFILENAME'})
=> #<Aws::EC2::Client>
```

### Current Behavior

Trying to initialize an AWS client with an SSO profile, we get an error: ` sso-session My Profile must be defined in the config file. Referenced by profile PROFILENAME (ArgumentError)`

```
$ irb -r aws-sdk-ec2
irb(main):001:0> Aws::EC2::Client.new({profile: 'PROFILENAME'})
/home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/shared_config.rb:364:in `sso_credentials_from_profile': sso-session My Profile must be defined in the config file. Referenced by profile PROFILENAME (ArgumentError)                                                             
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/shared_config.rb:153:in `sso_credentials_from_config'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:64:in `static_profile_sso_credentials'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:13:in `block in resolve'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/credentials_configuration.rb:72:in `block in <class:CredentialsConfiguration>'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:72:in `call'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:215:in `block in resolve_defaults'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:59:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:59:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:214:in `resolve_defaults'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:207:in `value_at'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:191:in `block in resolve'
        from /usr/lib/ruby/3.1.0/set.rb:511:in `each_key'
        from /usr/lib/ruby/3.1.0/set.rb:511:in `each'
        from /home/odeda/.local/share/gem/ruby/3.1.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/configuration.rb:191:in `resolve'
        ... 10 levels...
```

### Reproduction Steps

```
$ irb -r aws-sdk-ec2
irb(main):001:0> Aws::EC2::Client.new({profile: 'PROFILENAME'})
```

### Possible Solution

I have yet to find a fix for this. From reviewing the `lib/aws-sdk-core/shared_config.rb` file, I don't understand how SSO credentials are properly initialized, but it seems to be only when trying to "assume a role" (which I'm not sure when is that workflow triggered).

### Additional Information/Context

_No response_

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core

### Environment details (Version of Ruby, OS environment)

Ruby 3.1.0 on Ubuntu Lunar

### PR DESCRIPTION
**Pull request by alextwoods**
Fixes #2894 

The `aws configure sso` command will add quotes to sso-session names with whitespace.  Eg:
```
[sso-session 'My Profile']
```

This PR adds flexible support for loading those sso sessions (first checking for unquoted and then looking for the quoted version).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Review by jterapin — APPROVED** [review]

File: gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb [hunk 1]
```diff
@@ -469,5 +456,26 @@ def determine_profile(options)
...
+        sso_session = cfg["sso-session '#{sso_session_name}'"]
+      end
+
+      unless sso_session
+        raise ArgumentError,
+          "sso-session #{sso_session_name} must be defined in the config file. " \
+                    "Referenced by profile #{profile}"
+      end
+
+      unless sso_session['sso_region']
```
Comment (mullermp) [inline gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb:470]: `sso_credentials_from_profile` is not validating sso_region existing - SSO_CREDENTIAL_PROFILE_KEYS does not require sso_region. There is a branch that checks if it exists on profile and compares it to sso_region if present. I think this refactor is maybe breaking?

File: gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb [hunk 2]
```diff
@@ -469,5 +456,26 @@ def determine_profile(options)
       ret ||= 'default'
       ret
     end
+
+    def sso_session(cfg, profile, sso_session_name)
+      sso_session = cfg["sso-session #{sso_session_name}"]
+
+      if sso_session.nil? && sso_session_name.match(/\s/)
```
Comment (mullermp) [inline gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb]: You can possible just add an `|| cfg["sso-session '#{sso_session_name}'"]` after `cfg["sso-session #{sso_session_name}"]`

Comment (alextwoods) [reply gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb]: Yeah, we can skip the check for it containing whitespace and always use this check - I think thats reasonable and forwards compatible.

File: gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb (hunk 1 above)
Comment (alextwoods) [reply gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb:470]: The SSOCredentials will fail if sso_region is unset, so this moves the failure case up to here (with hopefully slightly. more info).

File: gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb [hunk 3]
```diff
@@ -389,7 +385,7 @@ def sso_credentials_from_profile(cfg, profile)
           sso_role_name: prof_config['sso_role_name'],
           sso_session: prof_config['sso_session'],
           sso_region: sso_region,
-          sso_start_url: prof_config['sso_start_url']
+          sso_start_url: sso_start_url
```
Comment (alextwoods) [inline gems/aws-sdk-core/lib/aws-sdk-core/shared_config.rb:388]: This change should be safe since the non-legacy flow does NOT use the sso_start_url, see: https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/sso_credentials.rb#L82

**Review by mullermp — APPROVED** [review]

**Comment by guss77** [comment]
Thank you - that indeed solves the issue I was having in #2894
