### PR TITLE
Filter sensitive params per service/type rather than a global list

### LINKED ISSUE #2312: list_tags_for_resource for Managed Instance does not return the list of tags
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
Invoking 
```
response = client.list_tags_for_resource(
    resource_type: "ManagedInstance",
    resource_id: "mi-1234567890",
  )
```

Returns:
```
{:tag_list=>[{:key=>"[FILTERED]", :value=>"[FILTERED]"}]}
```
which does not include the instance tags.

Invoking the same exact API call from AWS CLI returns my list of tags as I expected:

```
{
    "TagList": [
        {
            "Key": "ImageUrl",
            "Value": "XYZ"
        }
    ]
}
```

**Gem name**

```
aws-sdk-ssm (1.77.0)
aws-sdk-core (3.96.0)
```

**Version of Ruby, OS environment**
`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]`

**To Reproduce (observed behavior)**
Invoking 
```
response = client.list_tags_for_resource(
    resource_type: "ManagedInstance",
    resource_id: "mi-1234567890",
  )
```

**Expected behavior**
Return the tags of the ManagedInstance

**Additional context**
I am thinking maybe this is a "feature" to protect sensitive data, however I have not found a flag or any way for me to actually retrieve the tags. I expect/hope there is a way to get the tags and I haven't found it, otherwise the method should not exist in the first place.

### PR DESCRIPTION
**Pull request by mullermp**
Filters sensitive params only if they are marked in the type (via codegen)
Provide an option to disable sensitive param filtering if needed.

Fixes #2312, #2105, #2082

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb [hunk 1]
```diff
@@ -13,6 +13,17 @@ def format(pattern, options = {})
         Formatter.new(pattern, options).format(response)
       end
 
+      before do
```
Comment (mullermp) [inline gems/aws-sdk-core/spec/aws/log/formatter_spec.rb:16]: This is really gross - and also puts out many redefinitions.

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb [hunk 2]
```diff
@@ -13,6 +13,17 @@ def format(pattern, options = {})
...
+        class OperationRequestType < Struct
+          include Aws::Structure
+        end
+        OperationRequest = Seahorse::Model::Shapes::StructureShape.new(name: 'OperationRequest')
+        response.context.operation = Seahorse::Model::Operation.new.tap do |o|
+          o.input = Seahorse::Model::Shapes::ShapeRef.new(shape: OperationRequest)
+        end
+        OperationRequest.struct_class = OperationRequestType
+      end
```
Comment (mullermp) [inline gems/aws-sdk-core/spec/aws/log/formatter_spec.rb:25]: This is really gross and puts out many redefinitions

File: gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb [hunk 3]
```diff
@@ -6,40 +6,40 @@
...
+        else values
         end
       end
 
       private
 
-      def filter_hash(values)
+      def filter_hash(values, type)
+        filters = @additional_filters
+        if type.const_defined?('SENSITIVE')
```
Comment (alextwoods) [inline gems/aws-sdk-core/lib/aws-sdk-core/log/param_filter.rb:26]: Check type nil since its the default on filter. eg: `if type && type.const_defined?`

File: gems/aws-sdk-core/spec/aws/log/formatter_spec.rb [hunk 4]
```diff
@@ -7,12 +7,36 @@ module Aws
...
+          )
+        end
+        resp
+      end
 
       def format(pattern, options = {})
         Formatter.new(pattern, options).format(response)
       end
 
+      before do
```
Comment (alextwoods) [inline gems/aws-sdk-core/spec/aws/log/formatter_spec.rb:36]: Unused?

**Comment by mullermp** [comment]
eventstream needs investigation, this could break

File: build_tools/aws-sdk-code-generator/lib/aws-sdk-code-generator/views/types_module.rb [hunk 5]
```diff
@@ -253,23 +262,34 @@ def initialize(options)
...
+        attr_accessor :sensitive_params
+
         # @return [Boolean]
         def empty?
           @empty
         end
 
+        # @return [Boolean]
+        def sensitive_params?
+          @sensitive_params.any?
```
Comment (alextwoods) [inline build_tools/aws-sdk-code-generator/lib/aws-sdk-code-generator/views/types_module.rb:275]: I don't think this is a problem - but if sensitive_params isn't set at all on line 247, this will give an error.  To be safe I'd suggest having fetch have a default of []?

**Comment by mullermp** [comment]
Needs a plan for bumping versions..
