### PR TITLE
Ensure that the ReadCallbackIO is always unwrapped

### LINKED ISSUE #2761: S3 Gem firing undefined method rewind within Seahorse library
### Describe the bug

Utilizing the S3 gem, some file upload requests are getting caught into an unhandled exception from the Seahorse library during the retry handler.

### Expected Behavior

The request is retried without causing an exception to be thrown.

### Current Behavior

On Ruby 2.7.6 with the following S3 gems:
```
    aws-eventstream (1.2.0)
    aws-partitions (1.626.0)
    aws-sdk-core (3.140.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.525.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.56.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.114.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.5.1)
      aws-eventstream (~> 1, >= 1.0.2)
    jmespath (1.6.1)
```

Calling `Aws::S3::Resource.new(client: client).bucket(aws_bucket_name).object(path).upload_file(element_for_upload, metadata)` has been occasionally firing `undefined method 'rewind' for #<Seahorse::Client::Plugins::ReadCallbackIO:0x0000561a24493100>`
out from `aws-sdk-core (3.140.0) lib/aws-sdk-core/plugins/retry_errors.rb in retry_request`

Unfortunately our reporting software isn't setup to sample external libraries so recreating the full call stack without invoking a large invoice for S3 usage is infeasible.

### Reproduction Steps

Theoretically calling just
`Aws::S3::Resource.new(client: client).bucket(aws_bucket_name).object(path).upload_file(element_for_upload, metadata)` with valid arguments will occasionally reproduce the exception. We've only been able to see this about 400 times across the last 2 weeks so the randomness due to what we believe is networking is incredibly hard to track down.

### Possible Solution

The Seahorse library's `ReadCallbackIO` should either have a rewind method, or not be handled as it is being handled within the retry_errors library.

### Additional Information/Context

_No response_

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-core (3.140.0)

### Environment details (Version of Ruby, OS environment)

Ruby 2.7.6

### PR DESCRIPTION
**Pull request by alextwoods**
Fixes #2761 - ensure that the ReadCallbackIO is always unwrapped.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

**Review by mullermp — APPROVED** [review]
Needs changelog

File: gems/aws-sdk-core/lib/seahorse/client/plugins/request_callback.rb [hunk 1]
```diff
@@ -80,18 +80,16 @@ def call(context)
                 context.http_request.body,
                 callback
               )
-              add_event_listeners(context)
             end
-            @handler.call(context)
+            resp = @handler.call(context)
+            unwrap_callback_body(context)
```
Comment (mullermp) [inline gems/aws-sdk-core/lib/seahorse/client/plugins/request_callback.rb]: Does this need to happen all the time, or only if context[:on_chunk_sent] is set?

Comment (alextwoods) [reply gems/aws-sdk-core/lib/seahorse/client/plugins/request_callback.rb]: Only when on_chunk_sent is set, but unwrap already does a check, so not sure I want to nest this in another if?

Comment (alextwoods) [reply gems/aws-sdk-core/lib/seahorse/client/plugins/request_callback.rb]: Edit: did a bit of cleanup, not sure I have a preference for it or the other.
