### PR TITLE
Fix CloudFront `listConflictingAliasesMaxItemsInteger` is never used warning

### LINKED ISSUE #3179: Fix CloudFront client API unused variable
### Describe the bug

Hello. :wave: I'm seeing the following warning in my logs:

``` 
$HOME/.cache/frum/versions/3.4.1/lib/ruby/gems/3.4.0/gems/aws-sdk-cloudfront-1.109.0/lib/aws-sdk-cloudfront/client_api.rb:680: warning: assigned but unused variable - listConflictingAliasesMaxItemsInteger
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I would not expect to see this warning especially if `listConflictingAliasesMaxItemsInteger` is never used.

### Current Behavior

See above.

### Reproduction Steps

I would expect you'd be able to see this crop up in your test suite when adding the following to the top of your test suite:

``` ruby
$VERBOSE=true
```

### Possible Solution

If you delete `listConflictingAliasesMaxItemsInteger`, the issue will go away.

### Additional Information/Context

_No response_

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

 aws-sdk-cloudfront 1.109.0

### Environment details (Version of Ruby, OS environment)

ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin24.2.0]

### PR DESCRIPTION
**Pull request by richardwang1124**
Fixes https://github.com/aws/aws-sdk-ruby/issues/3179.

Customization in codegen for CloudFront was automatically setting the shape of `MaxItems` members to integers. Updated to only set the shape to integers when the shape was originally a string.

Running tests with current code and `$VERBOSE=true`
Screenshot 2025-02-05 at 12 33 35 PM

After change
Screenshot 2025-02-05 at 1 03 04 PM

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

File: gems/aws-sdk-cloudfront/lib/aws-sdk-cloudfront/client_api.rb [hunk 1]
```diff
@@ -2108,7 +2108,7 @@ module ClientApi
     ListConflictingAliasesRequest.add_member(:distribution_id, Shapes::ShapeRef.new(shape: distributionIdString, required: true, location: "querystring", location_name: "DistributionId"))
     ListConflictingAliasesRequest.add_member(:alias, Shapes::ShapeRef.new(shape: aliasString, required: true, location: "querystring", location_name: "Alias"))
     ListConflictingAliasesRequest.add_member(:marker, Shapes::ShapeRef.new(shape: string, location: "querystring", location_name: "Marker"))
-    ListConflictingAliasesRequest.add_member(:max_items, Shapes::ShapeRef.new(shape: integer, location: "querystring", location_name: "MaxItems"))
+    ListConflictingAliasesRequest.add_member(:max_items, Shapes::ShapeRef.new(shape: listConflictingAliasesMaxItemsInteger, location: "querystring", location_name: "MaxItems"))
```
Comment (alextwoods) [inline gems/aws-sdk-cloudfront/lib/aws-sdk-cloudfront/client_api.rb]: NIce - this does look like the correct change here. However, we typically don't include the code generated changes in the final PR that gets merged.  The release system itself will run the code generation and make the update from it.

**Review by alextwoods — COMMENTED** [review]
Nice - This looks good!  Just remove the change from runnning the code generator and it should be good to go.

File: gems/aws-sdk-cloudfront/lib/aws-sdk-cloudfront/client_api.rb (hunk 1 above)
Comment (richardwang1124) [reply gems/aws-sdk-cloudfront/lib/aws-sdk-cloudfront/client_api.rb]: Sounds good, I'll remove this then.

**Review by alextwoods — APPROVED** [review]
