### PR TITLE
Don't overwrite `host` header in sigv4 signer if given.

### LINKED ISSUE #2339: AWS::Sigv4::Signer overwrites 'host' header
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide for v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/index.html)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-ruby) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-ruby/issues) and didn't find any solution
  
**Describe the bug**
`AWS::Sigv4::Signer#sign_request`, when provided a `:headers` hash, overwrites the 'host' header. In my use case, I need to manually set the host in order to invoke a private API Gateway. Sending a request with a different host after creating the signature will invalidate the signature. I don't believe the `:unsigned_headers` option will help me here, because the 'host' header is [one of the ones that must be signed](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)

**Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version**
`aws-sigv4 (~> 1.0)`

**Version of Ruby, OS environment**
`ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]`

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)
```ruby
require 'aws-sigv4'

signed_request = Aws::Sigv4::Signer.new(
  service: 'execute-api',
  region: 'us-east-1',
  access_key_id: '',
  secret_access_key: ''
).sign_request(
  http_method: 'POST',
  url: 'http://wwww.domain.com/path',
  headers: { 'host' => 'host-header-value' },
  body: ''
)

signed_request.headers['host']
# => "wwww.domain.com"
```
**Expected behavior**
Expected the signer to create a signature using use the given 'host' value, if it exists 

**Screenshots**
N/A

**Additional context**
I've solved this locally by monkey-patching the method at the offending line here: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sigv4/lib/aws-sigv4/signer.rb#L222

```ruby
sigv4_headers['host'] = headers['host'] || host(url)
```

Will post a PR with a patch shortly too, but I wanted to post this issue first to confirm that it is actually a bug and not just a misunderstanding of this method.

### PR DESCRIPTION
**Pull request by aphillips19**
Closes #2339 

Makes sigv4's `Signer#sign_request` keep the original Host header if that header was given, instead of overwriting it with a host header from the URL. 

This also updates `Signer#presign_url`, which looks like it would have the same issue. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/master/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

File: gems/aws-sigv4/spec/signer_spec.rb [hunk 1]
```diff
@@ -144,6 +144,17 @@ module Sigv4
           expect(signature.headers['host']).to eq('domain.com')
         end
 
+        context 'when a Host header is provided' do
+          
+          let(:headers) { 'host' => 'custom-host-value' }
```
Comment (alextwoods) [inline gems/aws-sigv4/spec/signer_spec.rb:149]: It looks like you need to wrap this in an additional {}, ie: `let(:headers) {  { 'host' => 'custom-host-value' } } `

**Comment by mullermp** [comment]
Actually fix tests :D

**Comment by aphillips19** [comment]
> Actually fix tests :D

Thank you for actually actually fixing this! I had trouble running tests locally and was relying on the CI pipeline to catch my errors

**Comment by mullermp** [comment]
To run tests locally, you can use `rake test:spec`

**Comment by mullermp** [comment]
Thanks for the contribution!
