### PR TITLE
Remove checksums from default stubs

### LINKED ISSUE #2888: `Checksum validation failed` since aws-sdk-s3 1.132.0
### Describe the bug

Since aws-sdk-s3 1.132.0 (https://github.com/aws/aws-sdk-ruby/pull/2886 I suspect) the following code fails with the following error:

```ruby
$ cat tmp/aws-sdk-s3.rb
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "nokogiri"
  gem "aws-sdk-s3", ENV.fetch("SDK_VERSION", "1.132.0")
end

require "aws-sdk-s3"
require "tempfile"

Aws.config[:s3] = { stub_responses: true }

path = Tempfile.new.path
s3_bucket = Aws::S3::Resource.new.bucket("BUCKET")
s3_bucket.object("KEY").download_file(path)
```

```
$ SDK_VERSION=1.132.0 ruby tmp/aws-sdk-s3.rb
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using aws-eventstream 1.2.0
Using aws-partitions 1.794.0
Using aws-sigv4 1.6.0
Using bundler 2.4.13
Using racc 1.7.1
Using jmespath 1.6.2
Using nokogiri 1.15.3 (arm64-darwin)
Using aws-sdk-core 3.180.0
Using aws-sdk-kms 1.71.0
Using aws-sdk-s3 1.132.0
/Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:218:in `block in add_verify_response_checksum_handlers': Checksum validation failed on x-amz-checksum-SHA1 computed: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=, expected: ChecksumSHA1 (Aws::Errors::ChecksumError)
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/http/response.rb:146:in `block in on_success'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/http/response.rb:173:in `block in listener'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/http/response.rb:182:in `block in emit'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/http/response.rb:182:in `each'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/http/response.rb:182:in `emit'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/http/response.rb:112:in `signal_done'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/stub_responses.rb:98:in `signal_http'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/stub_responses.rb:68:in `apply_stub'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/stub_responses.rb:57:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/plugins/content_length.rb:24:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/streaming_retry.rb:71:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/s3_signer.rb:73:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/s3_host_id.rb:17:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/xml/error_handler.rb:10:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/sign.rb:49:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/s3_signer.rb:48:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/redirects.rb:20:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/user_agent.rb:37:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/http_checksum.rb:19:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:136:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/request_compression.rb:94:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/client_stubs.rb:36:in `block in setup_stubbing'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/expect_100_continue.rb:23:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/bucket_name_restrictions.rb:21:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/rest/handler.rb:10:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/endpoints.rb:41:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/endpoint_discovery.rb:84:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/skip_whole_multipart_get_checksums.rb:18:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/seahorse/client/request.rb:72:in `send_request'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/client.rb:6081:in `get_object'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/file_downloader.rb:163:in `single_request'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/file_downloader.rb:77:in `multipart_download'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/file_downloader.rb:41:in `block in download'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/file_downloader.rb:39:in `download'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/customizations/object.rb:512:in `block in download_file'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-core-3.180.0/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
	from /Users/dentarg/.arm64_rubies/3.2.2/lib/ruby/gems/3.2.0/gems/aws-sdk-s3-1.132.0/lib/aws-sdk-s3/customizations/object.rb:511:in `download_file'
	from tmp/aws-sdk-s3.rb:16:in `<main>'
```

### Expected Behavior

No failure, like it was using aws-sdk-s3 1.131.0

```
$ SDK_VERSION=1.131.0 ruby tmp/aws-sdk-s3.rb
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using aws-eventstream 1.2.0
Using aws-partitions 1.794.0
Using jmespath 1.6.2
Using aws-sigv4 1.6.0
Using bundler 2.4.13
Using racc 1.7.1
Using aws-sdk-core 3.180.0
Using nokogiri 1.15.3 (arm64-darwin)
Using aws-sdk-kms 1.71.0
Using aws-sdk-s3 1.131.0
```

### Current Behavior

See "Describe the bug"

### Reproduction Steps

See "Describe the bug"

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-s3

### Environment details (Version of Ruby, OS environment)

Ruby 3.2.2

### PR DESCRIPTION
**Pull request by alextwoods**
Fixes #2888 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

1. To make sure we include your contribution in the release notes, please make sure to add description entry for your changes in the "unreleased changes" section of the `CHANGELOG.md` file (at corresponding gem). For the description entry, please make sure it lives in one line and starts with `Feature` or `Issue` in the correct format.

2. For generated code changes, please checkout below instructions first:
  https://github.com/aws/aws-sdk-ruby/blob/version-3/CONTRIBUTING.md

Thank you for your contribution!

### CODE REVIEW

File: gems/aws-sdk-core/lib/aws-sdk-core/stubbing/stub_data.rb [hunk 1]
```diff
@@ -13,12 +13,23 @@ def initialize(operation)
...
         apply_data(data, stub)
         stub
       end
 
       private
 
+      def remove_checksums(stub)
+        if @rules && @rules.shape.is_a?(Seahorse::Model::Shapes::StructureShape)
+          @rules.shape.members.each do |key, member|
+            if member.location == 'header' && member.location_name.start_with?('x-amz-checksum-')
```
Comment (mullermp) [inline gems/aws-sdk-core/lib/aws-sdk-core/stubbing/stub_data.rb:26]: I think we should check for the trait, right? Will checksums always be headers, anywhere, and in the future?

Comment (alextwoods) [reply gems/aws-sdk-core/lib/aws-sdk-core/stubbing/stub_data.rb:26]: The checksums can be on a response without the trait (see s3 head_object).  They MUST be headers and they MUST start with 'x-amz-checksums-`

**Review by mullermp — APPROVED** [review]
